version: "3"

services:
  database:
    container_name: omero-database
    image: "postgres:14"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    container_name: omero-server
    image: "openmicroscopy/omero-server:5"
    env_file: 
      - ./.env
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_jvmcfg_percent_blitz: 50
      CONFIG_Ice_MessageSizeMax: 1000000
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    container_name: omero-web-standalone
    image: "openmicroscopy/omero-web-standalone:5"
    # build: https://github.com/vernonlim/omero-web-docker.git#master:standalone
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web_public_enabled: true
      CONFIG_omero_web_public_user: nottingham
      CONFIG_omero_web_public_password: nottingham
      CONFIG_omero_web_public_get__only: true
      CONFIG_omero_web_public_server__id: 1
      CONFIG_omero_web_public_url__filter: '^/(webadmin/myphoto/|webclient/(?!(script_ui|ome_tiff|figure_script))|webgateway/(?!(archived_files|download_as))|iviewer|api|omero_crm_landing_page)'
      CONFIG_omero_web_csrf__trusted__origins: '["https://omero.vernonlim.dev", "https://vernonlim.dev"]'
    networks:
      omero:
        aliases:
          - omeroweb
    ports:
      - "4080:4080"
    # expose:
    #   - "4080"
    volumes:
      - "../omero_crm_landing_page/omero_crm_landing_page:/opt/omero/web/venv3/lib/python3.9/site-packages/omero_crm_landing_page:ro"
      - "./config.omero:/opt/omero/web/config/config.omero:ro"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ../nginx/reverse_proxy.conf:/etc/nginx/nginx.conf
  #     - ../nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
  #     - ../nginx/vernonlim.dev.pem:/etc/nginx/cert/vernonlim.dev.pem
  #     - ../nginx/vernonlim.dev.key:/etc/nginx/cert/vernonlim.dev.key
  #   networks:
  #     - omero
  #   ports:
  #     - 80:80
  #     - 443:443

networks:
  omero:

volumes:
  database:
  omero:
